import React, { useState, useEffect } from 'react';
import { Activity, TrendingUp, Brain, Zap, Database, Clock, AlertTriangle } from 'lucide-react';

export function OverviewTab() {
  const [systemMetrics, setSystemMetrics] = useState({
    latency: 45,
    artifactSize: 2.3,
    dataFreshness: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    ensembleHealth: 98
  });

  const [marketRegime, setMarketRegime] = useState({
    sentiment: 'Bullish',
    volatility: 'Low',
    factors: ['Growth', 'Value']
  });

  const [neuralSignals, setNeuralSignals] = useState([
    { symbol: 'RELIANCE', signal: 'BUY', confidence: 0.87, timestamp: '14:32:15' },
    { symbol: 'TCS', signal: 'HOLD', confidence: 0.92, timestamp: '14:31:42' },
    { symbol: 'INFY', signal: 'SELL', confidence: 0.78, timestamp: '14:30:18' }
  ]);

  useEffect(() => {
    // Simulate real-time updates
    const interval = setInterval(() => {
      setNeuralSignals(prev => prev.map(signal => ({
        ...signal,
        confidence: Math.max(0.5, Math.min(1, signal.confidence + (Math.random() - 0.5) * 0.1))
      })));
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="bg-[#141415] border border-[#2d2d2d] rounded-2xl p-6 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-yellow-500"></div>
          <h2 className="text-[10px] font-bold text-yellow-500 uppercase tracking-[0.15em] flex items-center gap-2 mb-4">
            <Brain className="w-4 h-4" /> Build or analyze with the same decision engine
          </h2>
          <div className="space-y-4 text-xs text-[#86868b] leading-relaxed">
            <p><span className="font-bold text-[#f5f5f7]">Step 1:</span> Define the mandate based on your horizon and risk tolerance.</p>
            <p><span className="font-bold text-[#f5f5f7]">Step 2:</span> Review the recommended portfolio generated by the ensemble alpha models.</p>
            <p><span className="font-bold text-[#f5f5f7]">Step 3:</span> Compare it against your real holdings using the same institutional research stack.</p>
          </div>
        </div>

        <div className="bg-rose-500/10 border border-rose-500/30 rounded-2xl p-6 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-rose-500"></div>
          <h3 className="text-[10px] font-bold text-rose-500 uppercase tracking-[0.15em] flex items-center gap-2 mb-3">
            <AlertTriangle className="w-4 h-4" /> Bear Market Warning
          </h3>
          <p className="text-sm text-rose-400/90 leading-relaxed font-serif italic">
            "Current bear regime signals negative expected returns. Consider waiting for confirmation of trend reversal before deploying full capital."
          </p>
          <div className="mt-4 flex gap-2">
            <span className="px-2 py-0.5 rounded bg-rose-500/20 text-rose-400 text-[9px] font-mono uppercase tracking-wider border border-rose-500/30">High Risk Regime</span>
            <span className="px-2 py-0.5 rounded bg-[#141415] text-[#86868b] text-[9px] font-mono uppercase tracking-wider border border-[#2d2d2d]">Caution Advised</span>
          </div>
        </div>
      </div>

      <div className="overview-grid grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        {/* Ensemble Status */}
        <div className="bg-[#141415] border border-[#2d2d2d] rounded-2xl p-5">
          <div className="flex items-center gap-2 mb-4">
            <Brain className="w-4 h-4 text-yellow-500" />
            <h3 className="text-[10px] font-bold text-[#86868B] uppercase tracking-[0.08em]">Ensemble Status</h3>
          </div>
          <div className="ensemble-health mb-4">
            <div className="w-full h-1.5 bg-[#0a0a0a] rounded-full overflow-hidden mb-2">
              <div className="h-full bg-yellow-500" style={{ width: `${systemMetrics.ensembleHealth}%` }} />
            </div>
            <div className="text-[10px] font-mono text-[#86868b] uppercase tracking-wider">{systemMetrics.ensembleHealth}% Healthy</div>
          </div>
          <div className="space-y-2">
            {[
              { name: 'LightGBM Model', status: 'active' },
              { name: 'Rules Engine', status: 'active' },
              { name: 'News Sentiment', status: 'warning' }
            ].map(model => (
              <div key={model.name} className="flex items-center gap-2 text-[11px] text-[#f5f5f7]">
                <div className={`w-1.5 h-1.5 rounded-full ${model.status === 'active' ? 'bg-emerald-500' : 'bg-amber-500'}`} />
                <span>{model.name}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Market Regime Pulse */}
        <div className="bg-[#141415] border border-[#2d2d2d] rounded-2xl p-5">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-4 h-4 text-emerald-500" />
            <h3 className="text-[10px] font-bold text-[#86868B] uppercase tracking-[0.08em]">Market Regime Pulse</h3>
          </div>
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-[10px] text-[#86868b] uppercase font-mono">Sentiment</span>
              <span className="text-emerald-400 font-bold text-xs uppercase tracking-wider">{marketRegime.sentiment}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-[10px] text-[#86868b] uppercase font-mono">Volatility</span>
              <span className="text-yellow-500 font-bold text-xs uppercase tracking-wider">{marketRegime.volatility}</span>
            </div>
            <div className="pt-2 border-t border-[#2d2d2d]">
              <div className="flex flex-wrap gap-2">
                {marketRegime.factors.map(factor => (
                  <span key={factor} className="px-2 py-1 bg-[#0a0a0a] border border-[#2d2d2d] text-[#86868b] text-[9px] font-mono rounded uppercase">{factor}</span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Neural Signals */}
        <div className="bg-[#141415] border border-[#2d2d2d] rounded-2xl p-5 lg:col-span-2">
          <div className="flex items-center gap-2 mb-4">
            <Zap className="w-4 h-4 text-amber-500" />
            <h3 className="text-[10px] font-bold text-[#86868B] uppercase tracking-[0.08em]">Neural Signals</h3>
          </div>
          <div className="space-y-3">
            {neuralSignals.map((signal, index) => (
              <div key={index} className="flex items-center justify-between p-3 bg-[#0a0a0a] rounded-xl border border-[#2d2d2d] hover:border-yellow-500/30 transition-colors group">
                <div className="flex items-center gap-4">
                  <div className="font-bold text-[#f5f5f7] font-mono group-hover:text-yellow-500 transition-colors">{signal.symbol}</div>
                  <div className={`text-[10px] font-bold px-2 py-0.5 rounded ${signal.signal === 'BUY' ? 'bg-emerald-500/10 text-emerald-500' : signal.signal === 'SELL' ? 'bg-rose-500/10 text-rose-500' : 'bg-[#1d1d1f] text-[#86868b]'}`}>
                    {signal.signal}
                  </div>
                </div>
                <div className="flex items-center gap-6">
                  <div className="text-[10px] font-mono text-[#86868b] uppercase tracking-widest">{(signal.confidence * 100).toFixed(0)}% CONF</div>
                  <div className="text-[10px] font-mono text-[#6e6e73]">{signal.timestamp}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* System Metrics */}
      <div className="bg-[#141415] border border-[#2d2d2d] rounded-2xl p-6">
        <div className="flex items-center gap-2 mb-6">
          <Activity className="w-4 h-4 text-rose-500" />
          <h3 className="text-[10px] font-bold text-[#86868B] uppercase tracking-[0.08em]">System Architecture & Metrics</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="flex items-start gap-4 p-4 bg-[#0a0a0a] rounded-2xl border border-[#2d2d2d]">
            <Clock className="w-5 h-5 text-[#86868b]" />
            <div>
              <div className="text-lg font-bold text-[#f5f5f7] font-mono">{systemMetrics.latency}ms</div>
              <div className="text-[10px] text-[#86868b] uppercase font-mono tracking-wider">Avg Engine Latency</div>
            </div>
          </div>
          <div className="flex items-start gap-4 p-4 bg-[#0a0a0a] rounded-2xl border border-[#2d2d2d]">
            <Database className="w-5 h-5 text-[#86868b]" />
            <div>
              <div className="text-lg font-bold text-[#f5f5f7] font-mono">{systemMetrics.artifactSize}GB</div>
              <div className="text-[10px] text-[#86868b] uppercase font-mono tracking-wider">Neural Artifact Size</div>
            </div>
          </div>
          <div className="flex items-start gap-4 p-4 bg-[#0a0a0a] rounded-2xl border border-[#2d2d2d]">
            <Activity className="w-5 h-5 text-[#86868b]" />
            <div>
              <div className="text-lg font-bold text-[#f5f5f7] font-mono">{systemMetrics.dataFreshness}</div>
              <div className="text-[10px] text-[#86868b] uppercase font-mono tracking-wider">Research Freshness</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}